name: Build Python App for Desktop

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build .exe for Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build .exe with PyInstaller
      run: pyinstaller --onefile app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-app-windows
        path: dist/app.exe
